development:
  adapter: postgresql
  encoding: unicode
  database: nguyen-wired_development
  pool: 5
  username: Rebecca Nguyen
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: nguyen-wired_test
  pool: 5
  username: Rebecca Nguyen
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: nguyen-wired_production
  pool: 5
  username: Rebecca Nguyen
  password:
