development:
  adapter: postgresql
  encoding: unicode
  database: wired_development
  pool: 5
  username: Oanh
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: wired_test
  pool: 5
  username: Oanh
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: wired_production
  pool: 5
  username: Oanh
  password:
